* Jupyter
*** Clearing output cells from nb file
      This is needed when you want to commit your nb files to a VCS such as git or hg. One would like to save only the content 
      creation commands into the VCS.
      -  jupyter nbconvert --ClearOutputPreprocessor.enabled=True --clear-output <input.ipynb>
      -  jupyter nbconvert --ClearOutputPreprocessor.enabled=True --to notebook --stdout <input.ipynb > input_cleaned.ipynb
      
      The first command modifies the file in place because of the clear-output option (which also automatically sets the 
      --to notebook option). In the second, we can choose a different destination if desired
      In both cases, the ClearOutputPreprocessor needs to be enabled, or else the output cells continue to persist.
*** Displaying multiple variables from the same cell
      Use the following:
            from IPython.core.interactiveshell import InteractiveShell
            InteractiveShell.ast_node_interactivity = "all"
      This tells Jupyter to print the results for any variable or statement on it’s own line
*** Jupter tips and tricks
      - [[https://blogs.baruch.cuny.edu/cis3100/?p=40][Read this blog]]
